// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY4rKTPHP_ih0boNQaBZG8rniZTfkfYto',
    appId: '1:408566261169:web:0b54ed0e62ef86f5a68990',
    messagingSenderId: '408566261169',
    projectId: 'flutter-firebase-project-39b58',
    authDomain: 'flutter-firebase-project-39b58.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-39b58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS67It337gQa8Xq9alsV943VlkS2petzc',
    appId: '1:408566261169:android:a85800c8887432b6a68990',
    messagingSenderId: '408566261169',
    projectId: 'flutter-firebase-project-39b58',
    storageBucket: 'flutter-firebase-project-39b58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7EC9lDuTtN23_xGlQxh2SWnc9pI7ZhRQ',
    appId: '1:408566261169:ios:d9f1e685ae96b797a68990',
    messagingSenderId: '408566261169',
    projectId: 'flutter-firebase-project-39b58',
    storageBucket: 'flutter-firebase-project-39b58.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7EC9lDuTtN23_xGlQxh2SWnc9pI7ZhRQ',
    appId: '1:408566261169:ios:3c353116821740f1a68990',
    messagingSenderId: '408566261169',
    projectId: 'flutter-firebase-project-39b58',
    storageBucket: 'flutter-firebase-project-39b58.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseProjects.RunnerTests',
  );
}
